### ISSUE TITLE
Pass type to stylesheet

### ISSUE THREAD

**Issue by dkurchigin** [andreaspabst/vue3-head#1]
Hi, i want to use local css like this:

`
useHead({
      title: newTitle,
      charset: "utf-8",
      link: [
        {rel: "stylesheet", href: "./assets/css/bootstrap.min.css"},
      ],
  })
`

But, that doesn't work. 
In console:

`
Error: The stylesheet http://localhost:5173/assets/css/bootstrap.min.css was not loaded because its MIME type, "text/html", is not "text/css".
`

I want to use something like that:
`
 {rel: "stylesheet", href: "./assets/css/bootstrap.min.css", type: "text/css"}
`

**Comment by dkurchigin** [comment]
@andreaspabst @weilscoolis thx

**Comment by andreaspabst** [comment]
> {rel: "stylesheet", href: "./assets/css/bootstrap.min.css"

is the resource available? when you open http://localhost:5173/assets/css/bootstrap.min.css directly?

**Comment by dkurchigin** [comment]
> > {rel: "stylesheet", href: "./assets/css/bootstrap.min.css"
> 
> is the resource available? when you open http://localhost:5173/assets/css/bootstrap.min.css directly?

Thx! My bad

**Comment by dkurchigin** [comment]
Works good
